name: Bump UI tag(s)
on:
  workflow_dispatch:
    inputs:
      uitag:
        type: string
        description: "What UI tags needs to be used"

permissions:
  contents: write
  pull-requests: write

env:
  INPUT_UITAG: ${{ github.event.inputs.uitag }}

jobs:
  tag:
    name: Bump UI tags in Dockerfile
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Replace tags
        run: |
          sed -i '/CATTLE_UI_VERSION/s/.*/ENV CATTLE_UI_VERSION '"${INPUT_UITAG}"'/' package/Dockerfile
          sed -i '/CATTLE_DASHBOARD_UI_VERSION/s/.*/ENV CATTLE_DASHBOARD_UI_VERSION v'"${INPUT_UITAG}"'/' package/Dockerfile
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: "go generate"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          title: "[${{ github.ref_name }}] go generate"
          body: |
            Auto-generated by GitHub Actions create-pull-request
          labels: |
            status/auto-created
            status/uibump
      - name: Check outputs
        if: ${{ env.changes_exist == 'true' }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
