name: Go Generate
on: workflow_dispatch
jobs:
  go-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Run go-generate to fetch data.json
        run: make go-generate
      - name: Check for repository changes
        run: |
          if git diff --name-only --exit-code; then
            echo "No changes found in repository after 'go generate'"
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Changes found in repository after 'go generate':"
            git diff --name-only
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Create Pull Request
        if: ${{ env.changes_exist == 'true' }}
        id: cpr
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          commit-message: "go generate"
          branch-suffix: "short-commit-hash"
          delete-branch: true
          title: "[${{ github.ref_name }}] go generate"
          body: |
            Auto-generated by GitHub Actions create-pull-request
          labels: |
            status/auto-created
      - name: Check outputs
        if: ${{ env.changes_exist == 'true' }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
