name: Label issues
on:
  issues:
    types:
      - opened
      - reopened
      
permissions:
  issues: write
  
jobs:
  label_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Label issues
        id: run
        run: gh issue edit --add-label ${LABEL} ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LABEL: "bug"
