name: Replace value in file(s)
on:
  workflow_dispatch:
    inputs:
      filepath:
        type: string
        description: "What file(s) needs to be edited? Comma separated if multiple"
      replacevalue:
        type: string
        description: "What value needs to be edited?"
      newvalue:
        type: string
        description: "What value needs to be used?"
permissions:
  contents: write
  pull-requests: write

env:
  INPUT_FILEPATH: ${{ github.event.inputs.filepath }}
  INPUT_REPLACEVALUE: ${{ github.event.inputs.replacevalue }}
  INPUT_NEWVALUE: ${{ github.event.inputs.newvalue }}

jobs:
  tag:
    name: Replace environment variable in file
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Replace value
        run: |
          bash replace-value-in-file.sh ${INPUT_FILEPATH} ${INPUT_REPLACEVALUE} ${INPUT_NEWVALUE}
      - name: Check for repository changes
        run: |
          if git diff --name-only --exit-code; then
            echo "No changes found in repository"
            echo "changes_exist=false" >> $GITHUB_ENV
          else
            echo "Changes found in repository"
            git diff --name-only
            echo "changes_exist=true" >> $GITHUB_ENV
          fi
      - name: Create branch, commit and push
        if: ${{ env.changes_exist == 'true' }}
        id: branch
        run: |
          BRANCH="githubaction-replace-replacevalue-$(date +%Y-%m-%d-%H-%M-%S)"
          echo "::set-output name=branch::$BRANCH"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git checkout -b "$BRANCH"
          git commit -a -m "change value ${INPUT_REPLACEVALUE} to ${INPUT_NEWVALUE}"
          git push origin "$BRANCH"
      - name: Create Pull Request
        if: ${{ env.changes_exist == 'true' }}
        id: cpr
        uses: actions/github-script@v5.0.0
        env:
          SOURCE_BRANCH: ${{ steps.branch.outputs.branch }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { INPUT_REPLACEVALUE, INPUT_NEWVALUE } = process.env

            const { data: pr } = await github.rest.pulls.create({
              title: `[${{ github.ref_name }}] change value ${INPUT_REPLACEVALUE} to ${INPUT_NEWVALUE}`,
              body: 'Auto-generated by GitHub Actions',
              owner: context.repo.owner,
              repo: context.repo.repo,
              base: "${{ github.ref_name }}",
              head: `${ process.env.SOURCE_BRANCH }`
            });
            await github.rest.issues.addLabels({
              ...context.repo,
              issue_number: pr.number,
              labels: ["status/auto-created"],
            });
            console.log('Created new pull request');
            return pr.html_url;
      - name: Check outputs
        if: ${{ env.changes_exist == 'true' }}
        run: |
          echo "Pull Request URL - ${{ steps.cpr.outputs.result }}"
          echo "::notice file=.github,line=1,col=1::Pull Request URL - ${{ steps.cpr.outputs.result }}"
