name: Create RC tag
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: "What RC tag needs to be created"

permissions:
  contents: write
  git: write

jobs:
  tag:
    name: Add release tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const tag = '${{ github.event.inputs.tag }}';
            const tag_major_minor = /^(v\d+\.\d+)/.exec(tag);

            const branch = '${{ github.ref_name }}'

            const branch_major_minor = /^release\/(v\d+\.\d+)/.exec(branch);

            if(branch !=== tag) {
              return core.setFailed(`the tag major minor ${tag_major_minor} does not match branch major minor ${branch_major_minor}`);
            }


            try {
              const resp = await github.rest.git.getRef({...context.repo, ref: `tags/${tag}`});
              return core.setFailed(`the tag ${tag} already exists on ${resp.data.object.type} ${resp.data.object.sha}`);
            } catch(err) {
              if(err.status !== 404){
                throw err;
              }
            }

            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: context.sha
            })
