name: Update README
on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get chart index.yaml files
      run: |
       wget -O latest.index.yaml https://releases.rancher.com/server-charts/latest/index.yaml
       wget -O stable.index.yaml https://releases.rancher.com/server-charts/stable/index.yaml
    - name: Get version from latest index.yaml
      id: latestVersion
      uses: mikefarah/yq@master
      with:
        cmd: yq  '.entries.rancher[].appVersion | select(test("^v2.6") and select(. != "*-rc*"))' 'latest.index.yaml' | head -1
    - name: Get version from stable index.yaml
      id: stableVersion
      uses: mikefarah/yq@master
      with:
        cmd: yq  '.entries.rancher[].appVersion | select(test("^v2.6") and select(. != "*-rc*"))' 'stable.index.yaml' | head -1
    - name: Update README file
      run: |
       sed -i '/^\* Latest/ s/v2.6.[0-9]*/${{ steps.latestVersion.outputs.result }}/g' README.test
       sed -i '/^\* Stable/ s/v2.6.[0-9]*/${{ steps.stableVersion.outputs.result }}/g' README.test
    - name: Check for repository changes
      run: |
        if git diff --name-only --exit-code; then
          echo "No changes found in repository after updating README"
          echo "changes_exist=false" >> $GITHUB_ENV
        else
          echo "Changes found in repository after updating README:"
          git diff --name-only
          echo "changes_exist=true" >> $GITHUB_ENV
        fi
    - name: Create branch, commit and push
      if: ${{ env.changes_exist == 'true' }}
      id: branch
      run: |
        BRANCH="githubaction-update-readme-$(date +%Y-%m-%d-%H-%M-%S)"
        echo "::set-output name=branch::$BRANCH"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b "$BRANCH"
        git commit -a -m "update README with latest/stable"
        git push origin "$BRANCH"
    - name: Create Pull Request
      if: ${{ env.changes_exist == 'true' }}
      id: cpr
      env:
        SOURCE_BRANCH: ${{ steps.branch.outputs.branch }}
      uses: actions/github-script@v5.0.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          let body = 'Auto-generated by GitHub Actions'

          const { data: pr } = await github.rest.pulls.create({
            title: `[${{ github.ref_name }}] update README with latest/stable`,
            body: body,
            owner: context.repo.owner,
            repo: context.repo.repo,
            base: "${{ github.ref_name }}",
            head: `${ process.env.SOURCE_BRANCH }`
          });
          await github.rest.issues.addLabels({
            ...context.repo,
            issue_number: pr.number,
            labels: ["status/auto-created"],
          });
          console.log('Created new pull request');
          return pr.html_url;
    - name: Check outputs
      if: ${{ env.changes_exist == 'true' }}
      run: |
        echo "Pull Request URL - ${{ steps.cpr.outputs.result }}"
